name: Main workflow
on: [push]
jobs:
  lint:
    name: Static analysis by flake8 and mypy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Copy Pipfile for docker container
        run: |
          cp ./Pipfile ./.github/actions/lint/
          cp ./Pipfile.lock ./.github/actions/lint/
      - name: Static analysis
        uses: ./.github/actions/lint
  test:
    name: Unit testing by pytest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Copy python package source to docker container
        run: |
          cp -r ./python ./.github/actions/test/
          cp ./setup.py ./.github/actions/test/
          cp ./setup.cfg ./.github/actions/test/
          cp ./Pipfile ./.github/actions/test/
          cp ./Pipfile.lock ./.github/actions/test/
      - name: Unit test
        uses: ./.github/actions/test
