name: Main workflow
on: [push]
jobs:
  lint:
    name: Static analysis by flake8 and mypy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Copy requirements.txt for docker container
        run: |
          cp ./requirements.txt ./.github/actions/lint/
      - name: Static analysis
        uses: ./.github/actions/lint
  test:
    name: Unit testing by pytest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Copy requirements.txt for docker container
        run: |
          cp ./requirements.txt ./.github/actions/test/
      - name: Unit test
        uses: ./.github/actions/test
